[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["../lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 700
via_ir = true

remappings = [
    "forge-std/=../lib/forge-std/src/",
    "@openzeppelin/contracts/=../lib/openzeppelin-contracts/contracts/",
    "@1inch/solidity-utils/=../lib/solidity-utils/",
    "@1inch/aqua/=../lib/aqua/",
    "@1inch/swap-vm/=../lib/swap-vm/",
]
